<a href="https://colab.research.google.com/github/NikitaMalik2303/Banking_Churn_Prediction/blob/main/Churn_Modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.shape

(10000, 14)

In [5]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
X = df.iloc[:,3:-1].values
Y = df.iloc[:,-1].values

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [("encoder", OneHotEncoder(),[1])], remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [9]:
print(X[:10,:])

[[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]
 [0.0 0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]
 [1.0 0.0 0.0 502 0 42 8 159660.8 3 1 0 113931.57]
 [1.0 0.0 0.0 699 0 39 1 0.0 2 0 0 93826.63]
 [0.0 0.0 1.0 850 0 43 2 125510.82 1 1 1 79084.1]
 [0.0 0.0 1.0 645 1 44 8 113755.78 2 1 0 149756.71]
 [1.0 0.0 0.0 822 1 50 7 0.0 2 1 1 10062.8]
 [0.0 1.0 0.0 376 0 29 4 115046.74 4 1 0 119346.88]
 [1.0 0.0 0.0 501 1 44 4 142051.07 2 0 1 74940.5]
 [1.0 0.0 0.0 684 1 27 2 134603.88 1 1 1 71725.73]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))
ann.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

In [13]:
ann.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

In [14]:
ann.fit(X_train,Y_train, batch_size = 32, epochs = 30)

Epoch 1/30
250/250 [==============================] - 1s 2ms/step - loss: 0.5727 - accuracy: 0.7616
Epoch 2/30
250/250 [==============================] - 0s 2ms/step - loss: 0.4717 - accuracy: 0.7969
Epoch 3/30
250/250 [==============================] - 1s 3ms/step - loss: 0.4463 - accuracy: 0.8024
Epoch 4/30
250/250 [==============================] - 1s 4ms/step - loss: 0.4332 - accuracy: 0.8127
Epoch 5/30
250/250 [==============================] - 1s 4ms/step - loss: 0.4246 - accuracy: 0.8195
Epoch 6/30
250/250 [==============================] - 1s 4ms/step - loss: 0.4181 - accuracy: 0.8230
Epoch 7/30
250/250 [==============================] - 1s 3ms/step - loss: 0.4134 - accuracy: 0.8266
Epoch 8/30
250/250 [==============================] - 1s 4ms/step - loss: 0.4094 - accuracy: 0.8280
Epoch 9/30
250/250 [==============================] - 1s 3ms/step - loss: 0.4048 - accuracy: 0.8296
Epoch 10/30
250/250 [==============================] - 1s 4ms/step - loss: 0.3994 - accuracy: 0.8310

In [15]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred>0.5)

63/63 [==============================] - 0s 2ms/step


In [16]:
from sklearn.metrics import  confusion_matrix,accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
print(accuracy_score(Y_test, Y_pred))

[[1524   71]
 [ 201  204]]
0.864
